# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36519be2501c0f25f8342350d8dcfae5fa68f2fb3bbddebbbaab25d8b42916fc1a00ebfc4ef15efd69440b268688967a3b367d001a6302a0cf2552728ecaba70

test:
  secret_key_base: 89277b1c3d0178d281d9591ef4d9ff2ebb6cdcd51df4c155fc7779443a240342ca26b9e19df59f881e2fab10f88afe1de80b072b9622d3793b07052754b08e1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
